<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU</Platforms>
    <AssemblyName>iiv_view</AssemblyName>
    <RootNamespace>iiv_view</RootNamespace>
    <BaseOutputPath></BaseOutputPath>
  </PropertyGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy &quot;$(OutDir)iiv_view.*&quot; &quot;$(SolutionDir)$(Configuration)\&quot;" />
  </Target>
</Project>
